service: ${self:provider.stage}-spotify-auth-lambda

frameworkVersion: '2'

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: './webpack.config.js'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ca-central-1

functions:
  login:
    handler: 'handler.login'
    description: 'Login to spotify account and get an access token.'
    events:
      - http:
          method: 'get'
          path: 'login'

  callback:
    handler: 'handler.callback'
    description: 'Callback to spotify authorization to get an access token.'
    events:
      - http:
          method: 'get'
          path: 'callback'